### PR TITLE
Adds support for bearer token authentification

### PR DESCRIPTION
**Pull request by korotkoff**
This change is [Reviewable](https://reviewable.io/reviews/springboardretail/springboard-client-ruby/9)

### CODE REVIEW

**Comment by jstotz** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[README.md, line 32 \[r1\]](https://reviewable.io:443/reviews/springboardretail/springboard-client-ruby/9#-KGON6_Z174cyWmKLqSC:-KGON6_Z174cyWmKLqSD:-1848395099) ([raw file](https://github.com/springboardretail/springboard-client-ruby/blob/880e8caf0515d240f0a5da432124cb07b4add71a/README.md#L32)):*
Let's use `token: 'secret_token'` hash syntax.

---

*[lib/springboard/client.rb, line 73 \[r1\]](https://reviewable.io:443/reviews/springboardretail/springboard-client-ruby/9#-KGOMeFn11s8LOUuJLsx:-KGOMeFn11s8LOUuJLsy:-1920544245) ([raw file](https://github.com/springboardretail/springboard-client-ruby/blob/880e8caf0515d240f0a5da432124cb07b4add71a/lib/springboard/client.rb#L73)):*
There's actually a YARD tag for this that you should use instead: http://www.rubydoc.info/gems/yard/file/docs/Tags.md#deprecated

---

*[lib/springboard/client.rb, line 83 \[r1\]](https://reviewable.io:443/reviews/springboardretail/springboard-client-ruby/9#-KGOMWM_nN9Fu4QcxYDV:-KGOMWM_nN9Fu4QcxYDW:-321329008) ([raw file](https://github.com/springboardretail/springboard-client-ruby/blob/880e8caf0515d240f0a5da432124cb07b4add71a/lib/springboard/client.rb#L83)):*
Let's use `token: 'secret_token'` style syntax instead since we only support Ruby 1.9+

I'm planning on running Rubocop to update the codebase itself but we might as well have the message use the newer syntax.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/springboardretail/springboard-client-ruby/9)*

**Comment by jstotz** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/springboardretail/springboard-client-ruby/9)*

**Comment by jstotz** [comment]
There's a typo in the commit message "authentiction" -> "authentication"

Also, can you please reference the issue # from the commit message to link it to the PR.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/springboardretail/springboard-client-ruby/9#-:-KGOR-7UHOlZ2cUlX_R6:-682678297)*

**Comment by korotkoff** [comment]
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[README.md, line 32 \[r1\]](https://reviewable.io:443/reviews/springboardretail/springboard-client-ruby/9#-KGON6_Z174cyWmKLqSC:-KGOSvSmBLKNQ4VnQRfp:-499146009) ([raw file](https://github.com/springboardretail/springboard-client-ruby/blob/880e8caf0515d240f0a5da432124cb07b4add71a/README.md#L32)):*
Done.

---

*[lib/springboard/client.rb, line 73 \[r1\]](https://reviewable.io:443/reviews/springboardretail/springboard-client-ruby/9#-KGOMeFn11s8LOUuJLsx:-KGOSwB6cEBY1Mo-0lx2:-499146009) ([raw file](https://github.com/springboardretail/springboard-client-ruby/blob/880e8caf0515d240f0a5da432124cb07b4add71a/lib/springboard/client.rb#L73)):*
Done.

---

*[lib/springboard/client.rb, line 83 \[r1\]](https://reviewable.io:443/reviews/springboardretail/springboard-client-ruby/9#-KGOMWM_nN9Fu4QcxYDV:-KGOSx0aprY9gFjg15Iy:-499146009) ([raw file](https://github.com/springboardretail/springboard-client-ruby/blob/880e8caf0515d240f0a5da432124cb07b4add71a/lib/springboard/client.rb#L83)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/springboardretail/springboard-client-ruby/9)*

**Comment by jstotz** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/springboardretail/springboard-client-ruby/9)*

**Pull request merged**
